# Generated by Django 5.0.9 on 2024-11-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
