# Generated by Django 5.0.9 on 2024-12-10 13:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('display', models.CharField(choices=[('admin', 'Admin'), ('attendee', 'Attendee'), ('organizer', 'Organizer'), ('speaker', 'Speaker')], help_text='User role display name', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.OneToOneField(help_text='User role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.userrole'),
        ),
    ]
