# Generated by Django 5.0.9 on 2025-05-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                default="User", help_text="First name", max_length=255
            ),
        ),
    ]
