# Generated by Django 5.0.9 on 2024-11-14 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0002_alter_attendee_is_verified'),
        ('events', '0007_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('overall_rating', models.IntegerField()),
                ('engagement', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('content_depth', models.IntegerField()),
                ('speaker_knowledge', models.IntegerField()),
                ('practical_relevance', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.attendee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
