# Generated by Django 5.0.9 on 2025-06-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendees", "0002_initial"),
        ("events", "0006_alter_session_event_alter_session_speaker"),
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
            },
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.UniqueConstraint(
                fields=("session", "attendee"),
                name="unique_feedback_per_attendee_session",
            ),
        ),
    ]
