repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: 'migrations/|tests.py|.*tests.py'
      - id: end-of-file-fixer
        exclude: 'migrations/|tests.py|.*tests.py'
      - id: check-yaml
        exclude: 'migrations/|tests.py|.*tests.py'
      - id: check-json
        exclude: 'migrations/|tests.py|.*tests.py'

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.12
        exclude: 'migrations/|tests.py|.*tests.py'

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-django]
        exclude: 'migrations/|tests.py|.*tests.py'

