# Generated by Django 5.0.9 on 2025-08-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='The organizer who created this event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='organizers.organizers'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_country', to='events.country'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_location', to='events.location'),
        ),
        migrations.AddField(
            model_name='session',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='events.event'),
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_location', to='events.location'),
        ),
    ]
