# Generated by Django 5.0.9 on 2025-06-03 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="event",
        ),
        migrations.RemoveField(
            model_name="region",
            name="country",
        ),
        migrations.AddField(
            model_name="country",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="events.region",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.country",
            ),
        ),
    ]
