# Generated by Django 5.0.9 on 2025-06-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_tag_event_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="short_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Brief description for event cards",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="website",
            field=models.URLField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed description for event page",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_nickname",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
