# Generated by Django 5.0.9 on 2025-08-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_region_event_tags_session_speaker_location_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="region",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
