# Generated by Django 5.0.9 on 2025-06-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_image'),
        ('speakers', '0003_delete_handles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='events.event'),
        ),
        migrations.AlterField(
            model_name='session',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaking_sessions', to='speakers.speakerprofile'),
        ),
    ]
