# Generated by Django 5.0.9 on 2025-07-04 10:54

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_session_event_alter_session_speaker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="documents/",
            ),
        ),
    ]
