# Generated by Django 5.0.9 on 2025-08-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_document"),
        ("organizers", "0005_sociallinks_delete_organizerssociallinks"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                help_text="The organizer who created this event",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to="organizers.organizers",
            ),
        ),
    ]
