# Generated by Django 5.0.9 on 2025-02-16 16:13

import cloudinary.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_event_image_event_event_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.FileField(default=1, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
