# Generated by Django 5.1.7 on 2025-03-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_document_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
