services:
  - type: web
    name: speakwise
    env: python
    buildCommand: pip install -r requirements/base.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ADMIN_URL
        value: admin/
      - key: CLOUDINARY_CLOUD_NAME
        value: deaxcci9a
      - key: CLOUDINARY_API_KEY
        value: 352423298968638
      - key: CLOUDINARY_API_SECRET
        value: YnnCROcEsMeGHXDVEb9u-wqgpo4
      - key: DATABASE_URL
        fromDatabase:
          name: speakwise-db
          property: connectionString

databases:
  - name: speakwise-db
    databaseName: speakwise
    user: speakwise
