# Generated by Django 5.0.9 on 2024-11-22 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizers',
            name='socials',
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizers_social_accounts', to='organizers.organizers'),
        ),
    ]
