# Generated by Django 5.0.9 on 2024-11-22 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_remove_organizers_socials_sociallinks_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
