# Generated by Django 5.0.9 on 2025-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_skilltag_speakerprofile_speakerdashboard_handles_and_more'),
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='speaker_id',
            field=models.ManyToManyField(to='speakers.speakerprofile'),
        ),
    ]
