# Generated by Django 5.0.9 on 2024-10-30 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_country_region_remove_event_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('end_date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('speaker', models.CharField(max_length=255, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
