# Generated by Django 5.0.9 on 2025-01-30 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_event_image_event_event_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='events.event'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='events.country'),
        ),
    ]
