# Generated by Django 5.0.9 on 2024-11-07 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0007_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_name", models.CharField(blank=True, max_length=50)),
                ("social_link", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "db_table": "Social Link ",
                "ordering": ["social_name"],
            },
        ),
        migrations.CreateModel(
            name="Organizers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("organization", models.CharField(max_length=100)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="organizers/avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "events",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizers",
                        to="events.event",
                        verbose_name="events",
                    ),
                ),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "socials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizers.sociallinks",
                        verbose_name="social links",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizer",
                "verbose_name_plural": "Organizers",
                "db_table": "organizers",
            },
        ),
    ]
