# Generated by Django 5.0.9 on 2025-07-01 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizersSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('social_name', models.CharField(max_length=50)),
                ('social_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizers_social_accounts', to='organizers.organizers')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
