# Generated by Django 5.0.9 on 2024-11-22 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_session'),
        ('organizers', '0003_sociallinks_created_at_sociallinks_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizers',
            name='avatar',
            field=models.ImageField(max_length=255, null=True, upload_to='organizers/avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='organizers',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='events.event', verbose_name='events'),
        ),
        migrations.AlterField(
            model_name='organizers',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='social_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='social_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
