# Generated by Django 5.0.9 on 2025-07-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0003_attendeecsvupload"),
        ("organizers", "0003_organizerssociallinks_delete_sociallinks"),
    ]

    operations = []
