# Generated by Django 5.1.7 on 2025-03-29 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_country_options'),
        ('organizers', '0004_alter_organizers_avatar_alter_organizers_events_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_attendance_emails', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
