# Generated by Django 5.0.9 on 2025-08-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_sociallinks_delete_organizerssociallinks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sociallinks',
            table='Social Link ',
        ),
    ]
