# Generated by Django 5.1.7 on 2025-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_attendanceemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceemails',
            name='is_given_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendanceemails',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
