name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8

    - name: Set up Database
      run: |
        cd backend
        python manage.py migrate
      env:
        DJANGO_SETTINGS_MODULE: speakwise.settings
        PYTHONPATH: ${{ github.workspace }}/backend

    - name: Run Black Formatter
      run: |
        cd backend
        black --check .  # Check formatting using black
      env:
        PYTHONPATH: ${{ github.workspace }}/backend

    - name: Run Flake8 Linter
      run: |
        cd backend
        flake8 .  # Run linting using flake8
      env:
        PYTHONPATH: ${{ github.workspace }}/backend

    - name: Run Tests
      run: |
        cd backend
        python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: speakwise.settings
        PYTHONPATH: ${{ github.workspace }}/backend
