# Generated by Django 5.1.7 on 2025-05-09 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('social_name', models.CharField(max_length=50, null=True)),
                ('social_link', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Social Media Handle',
                'verbose_name_plural': 'Social Media Handles',
                'db_table': 'Handles',
                'ordering': ['social_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'skill_tag',
            },
        ),
        migrations.CreateModel(
            name='SpeakerSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('social_name', models.CharField(max_length=50)),
                ('social_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Speaker Social Link',
                'verbose_name_plural': 'Speaker Social Links',
                'ordering': ['display_order', 'social_name'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_dashboard', to='feedbacks.feedback')),
            ],
            options={
                'db_table': 'speaker_dashboard',
            },
        ),
        migrations.CreateModel(
            name='SpeakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('short_bio', models.CharField(blank=True, max_length=255)),
                ('long_bio', models.TextField()),
                ('country', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to='speakers/avatars/')),
                ('events_spoken', models.ManyToManyField(blank=True, related_name='speakers', to='events.event')),
                ('skill_tags', models.ManyToManyField(blank=True, to='speakers.skilltag')),
            ],
            options={
                'db_table': 'speaker_profile',
            },
        ),
    ]
