# Generated by Django 5.0.9 on 2024-12-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='twitter',
        ),
    ]
