# Generated by Django 5.1.7 on 2025-05-09 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerprofile',
            name='speaker_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speakerdashboard',
            name='speaker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_dashboard', to='speakers.speakerprofile'),
        ),
        migrations.AddField(
            model_name='handles',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='speakers_social_accounts', to='speakers.speakerprofile'),
        ),
        migrations.AddField(
            model_name='speakersociallink',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='speakers.speakerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='speakersociallink',
            unique_together={('speaker', 'social_name')},
        ),
    ]
