# Generated by Django 5.1.7 on 2025-05-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Handles',
        ),
    ]
