# Generated by Django 5.0.9 on 2024-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_remove_speaker_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=50, null=True)),
                ('social_link', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Handle',
                'verbose_name_plural': 'Handles',
                'db_table': 'handles',
            },
        ),
        migrations.AddField(
            model_name='speaker',
            name='social_handles',
            field=models.ManyToManyField(related_name='speakers', to='speakers.handles'),
        ),
    ]
