# Generated by Django 5.0.9 on 2024-12-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_handles_speaker_social_handles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='social_handles',
        ),
        migrations.DeleteModel(
            name='Handles',
        ),
    ]
