# Generated by Django 5.0.9 on 2025-07-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_delete_handles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakersociallink',
            old_name='social_url',
            new_name='social_link',
        ),
    ]
