# Generated by Django 5.0.9 on 2024-12-13 14:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0004_remove_speaker_social_handles_delete_handles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('social_name', models.CharField(max_length=50, null=True)),
                ('social_link', models.URLField(null=True)),
                ('speakers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='speakers_social_accounts', to='speakers.speaker')),
            ],
            options={
                'verbose_name': 'Handles',
                'verbose_name_plural': 'Handles',
                'db_table': 'Handles ',
                'ordering': ['social_name'],
            },
        ),
    ]
