# Generated by Django 5.0.9 on 2025-08-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0004_rename_social_url_speakersociallink_social_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="speakersociallink",
            old_name="social_link",
            new_name="social_url",
        ),
    ]
