# Generated by Django 5.0.9 on 2024-12-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_session'),
        ('feedbacks', '0001_initial'),
        ('speakers', '0005_handles'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='speakers', to='events.event'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbacks.feedback'),
        ),
    ]
