# Generated by Django 5.0.9 on 2024-12-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0006_speaker_event_speaker_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='user',
            new_name='speaker_user',
        ),
    ]
